### ISSUE TITLE
License of dataset

### ISSUE THREAD

**Issue by kjappelbaum** [cnedwards/text2mol#2]
Hi 👋🏼

We were looking into reusing your dataset. Could you please advise us about the license under which you release the dataset? 

Many thanks, 
Kevin

**Comment by cnedwards** [comment]
Hi,

The underlying license for the raw data is CC BY 4.0 (and PubChem is Public Domain).

If it would help to release the dataset under a license, I'd be happy to look into doing so.  I'm planning to join tomorrow's meeting if you want to discuss then.
