### ISSUE TITLE
SDF files are no longer available

### ISSUE THREAD

**Issue by chunchiehy** [cnedwards/text2mol#3]
Hi, 

It seems that SDF files are no longer available due to the following error when i tried to fetch the data:

`batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
`

Thanks in advance

**Comment by cnedwards** [comment]
Hello,

I added a file "training.sdf.zip" which should download without Github LFS. The other sdf files should be under Github's limit, but please reopen the issue if they cannot be downloaded.

**Comment by chunchiehy** [comment]
Hello, thank you so much for the quick response! I successfully downloaded "training.sdf.zip". However, for the valid and test sdf files, it shows still the same problem. Would you mind also uploading the other files? Thanks a lot!

**Comment by cnedwards** [comment]
I added zipped versions of those files.

**Comment by chunchiehy** [comment]
Thanks a lot for your help. Have a nice day!
